### ISSUE TITLE
[bug] clone 后 npm install 运行项目，样式引入提示错误  

### ISSUE THREAD

**Issue by Alicehhhmm** [nihaojob/vue-fabric-editor#299]
node: 16.16.0 、18.16.0  
   
```bash
[less] missing semi-colon or unrecognised media features on import                                                                                                                                                14:04:39  


 ERROR  14:04:39 [vite] Internal server error: [less] missing semi-colon or unrecognised media features on import                                                                                                         14:04:39  
  Plugin: vite:css
  File: xxxx/vue-fabric-editor/src/styles/index.less:1:0
  1  |  @import '~view-ui-plus/src/styles/index.less';
     |  ^
  2  |  @import './resetViewUi.less';
  3  |  // view-ui iconfont (404问题 https://github.com/view-design/ViewUIPlus/issues/212)
      at less (file:///C:/Users/%E9%BB%84%E5%BA%AD%E6%B5%A9/Dev-project/Github-PRCodeing/vue-fabric-editor/node_modules/vite/dist/node/chunks/dep-68d1a114.js:39494:33)
      at async compileCSSPreprocessors (file:///C:/Users/%E9%BB%84%E5%BA%AD%E6%B5%A9/Dev-project/Github-PRCodeing/vue-fabric-editor/node_modules/vite/dist/node/chunks/dep-68d1a114.js:38770:30)
      at async compileCSS (file:///C:/Users/%E9%BB%84%E5%BA%AD%E6%B5%A9/Dev-project/Github-PRCodeing/vue-fabric-editor/node_modules/vite/dist/node/chunks/dep-68d1a114.js:38820:36)
      at async TransformContext.transform (file:///C:/Users/%E9%BB%84%E5%BA%AD%E6%B5%A9/Dev-project/Github-PRCodeing/vue-fabric-editor/node_modules/vite/dist/node/chunks/dep-68d1a114.js:38300:56)
      at async Object.transform (file:///C:/Users/%E9%BB%84%E5%BA%AD%E6%B5%A9/Dev-project/Github-PRCodeing/vue-fabric-editor/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44352:30)
      at async loadAndTransform (file:///C:/Users/%E9%BB%84%E5%BA%AD%E6%B5%A9/Dev-project/Github-PRCodeing/vue-fabric-editor/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55026:29)
      at async viteTransformMiddleware (file:///C:/Users/%E9%BB%84%E5%BA%AD%E6%B5%A9/Dev-project/Github-PRCodeing/vue-fabric-editor/node_modules/vite/dist/node/chunks/dep-68d1a114.js:64430:32)
```

**Comment by Qiu-Jun** [comment]
vite配置全局less符号问题，晚点有空更新

**Comment by liwenshuo1** [comment]
我也是。less删了以后还有各种报错 ，折腾半天也没启动项目

**Comment by Qiu-Jun** [comment]
> 我也是。less删了以后还有各种报错 ，折腾半天也没启动项目

重新拉最新代码试试

**Comment by Qiu-Jun** [comment]
> 重新拉最新代码试试

重新拉最新代码试试

**Comment by liwenshuo1** [comment]
> > 我也是。less删了以后还有各种报错 ，折腾半天也没启动项目
> 
> 重新拉最新代码试试

好了，好了
